### ISSUE TITLE
Void net-install bug with old ISO

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-mklive#100]
Hi !
Using the old void-live-i686-20160420.iso we have a big problem with a fresh net-install as you can see on the forum: https://forum.voidlinux.eu/t/void-installer-bug/1906

Only the root account is created. The normal user account is not created !
Bug in void-installer script ?

Maybe the ISO images in https://repo.voidlinux.eu/live/current/ are too old to install the current Void system, as @Duncaen has advised me here: https://github.com/voidlinux/void-packages/issues/5755

**Comment by Duncaen** [comment]
No!
