### ISSUE TITLE
New void-live-x86_64-musl Cinnamon ISO is needed!!

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-mklive#104]
Hi !

I think a new void-live-x86_64-musl Cinnamon ISO is needed.

With the current ISO (https://repo.voidlinux.eu/live/current/void-live-x86_64-musl-20170220-cinnamon.iso) Cinnamon crashes.

I get this [error message](https://voidlinuxforum.s3.amazonaws.com/original/1X/f45868a43fd8f9d3a1bc228c01114071126fe1da.jpg) ...

We are at least 2 different persons facing similar problem, tested on different hardware platforms with the same result. 
:( 

Thank you.

**Comment by cr6void** [comment]
Well, nobody cares ? So I close this issue.

On the [download page](http://www.voidlinux.eu/download/#download-installable-base-live-images-x86) we should, at least, add a **warning** like this: "Don't use Cinnamon x86_64-musl ISO because it's buggy."

**Comment by sholwe** [comment]
This issue should still be open, as the current (Feb) build doesn't work.   I'm sure it's low priority, but eventually it will be looked into.
