### ISSUE TITLE
mklive.sh does not build native live image on x86_64-musl

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-mklive#106]
**Example** 
Build a native live image with runit and keyboard set to 'fr': 

`# ./mklive.sh -k fr`

On my Void x86_64-musl, this command does not build a x86_64-musl live image. 
Instead of that, this command generates a glibc x86_64 image. 

I think the problem is at [line322](https://github.com/voidlinux/void-mklive/blob/master/mklive.sh.in#L322) in mklive.sh:

`# Set defaults`
`: ${BASE_ARCH:=$(uname -m)}`

On my x86_64-musl system, the command `uname -m` returns: 

`$ uname -m`
`x86_64`

So, mklive.sh can't see the difference between musl & glibc on x86_64 ! 
Regards.

**Comment by Gottox** [comment]
replace that line with `: ${BASE_ARCH:=$(xbps-uhelper arch 2>/dev/null || uname -m)`

Does this help?

**Comment by cr6git** [comment]
`# ./mklive.sh -k fr`
`./mklive.sh: 322: ./mklive.sh: Syntax error: Missing '}'`

You forgot the "}" at the end of the new line. 
I added the missing "}" and now it works fine! 
Thank you @Gottox
