### ISSUE TITLE
Can't delete first character on LiveCD login

### ISSUE THREAD

**Issue by ledoge** [voidlinux/void-mklive#114]
I built an ISO on x86_64 with the default settings by just running ./mklive.sh; this bug does not occur on the ISO provided on the website.

Steps to reproduce the bug:
1. Boot the LiveCD and wait for the login prompt
2. Type any amount of characters
3. Hit backspace

No matter how often I hit backspace, the first character I entered never gets deleted. So if I typo'd it, I have to hit enter twice and wait until I can login again. This issue does not occur on login attempts after that.

**Comment by cr6git** [comment]
I confirm. You are absolutely right.

**Comment by the-maldridge** [comment]
Can you confirm that the character is actually in the input buffer and not just being ghosted on to the screen?  It is not uncommon for the login prompt's readline buffer to get out of sync with the tty itself.

**Comment by cr6git** [comment]
@the-maldridge The same on tty2, tty3, tty4, ...

**Comment by the-maldridge** [comment]
> @the-maldridge The same on tty2, tty3, tty4, ...

This doesn't answer if the character is actually there or just ghosting.

**Comment by cr6git** [comment]
@the-maldridge Sorry, how can I see that ? What is the command ?

**Comment by the-maldridge** [comment]
hit some characters, backspace until you can't delete the "first" character, then try to login.  If my suspicion is correct then you will be able to login without issue even though your username doesn't appear correct.

**Comment by cr6git** [comment]
@the-maldridge No, I am not able to login. 
So, if I understand correctly what you described, the character is not ghosting, it's actually in the input buffer.

**Comment by the-maldridge** [comment]
That does sound like that is the case.  I'm not sure what would cause that to be an issue, but I'm all ears if anyone has suggestions for how there could be an undeletable character in the buffer.

**Comment by cr6git** [comment]
@the-maldridge I just found [this issue](https://github.com/karelzak/util-linux/issues/454).

**Comment by the-maldridge** [comment]
Sounds like we need to hurry up and wait.

**Comment by cr6git** [comment]
I just built a new ISO and it's fixed now ! :) 
You can close this issue.
