### ISSUE TITLE
musl LXQT ISO comes with a broken web browser

### ISSUE THREAD

**Issue by tac1ica** [voidlinux/void-mklive#120]
Besides #104, this image is also somewhat bad PR for the project, as the QupZilla browser is unusable; it crashes on startup every single time, at least on x86_64. You have to install the ISO on purpose just to be able to replace it with a working browser.

> /builddir/qt-everywhere-opensource-src-5.8.0/qtwebengine/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:clone() failure
> Received signal 11 SEGV_MAPERR 0000007d0f00
>  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
> r12: 00007fd92a0bb8c8 r13: 00007fffee2932f0 r14: 00007fd92a0bb780 r15: 00007fd93c9d92e2
>  di: 0000000000000001  si: 00007fd93b91c720  bp: 0000000000000001  bx: 00007fffee2932f0
>  dx: 00007fd93cc09b50  ax: 00000000007d0f00  cx: 0000000000000000  sp: 00007fffee2932d0
>  ip: 00007fd93a602c41 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000006
> trp: 000000000000000e msk: 0000000000000000 cr2: 00000000007d0f00
>[end of stack trace]

**Comment by the-maldridge** [comment]
Please open a ticket against the qupzilla package in the void-packages repository.  This issue tracker is for specific problems with the install environment and the live media, not packages contained therein.

**Comment by Gottox** [comment]
This issue can be resolved by replacing/removing the browser from the install medium. Those are two different issues imho.

**Comment by tac1ica** [comment]
In either case the "real" fix would come in the form of a new set of ISOs, hence my originally placing this report here. Anyway, I filed https://github.com/voidlinux/void-packages/issues/7051 already as requested.

**Comment by Vaelatern** [comment]
New ISOs published. Move to close issue.
