### ISSUE TITLE
Live on virtualbox gives black screen

### ISSUE THREAD

**Issue by Zac610** [voidlinux/void-mklive#132]
I have downloaded void-live-x86_64-musl-20170220-lxqt.iso, I have created a 512MB RAM 2GB HD system and used the iso as cdrom partition. It does boot to desktop, but any action I perform clicking mouse, the screen goes blank and no other visible action can be performed.

I am on windows 7, Virtualbox Version 5.0.32 r112930

**Comment by the-maldridge** [comment]
This turned out to be an Xorg problem which has since been resolved, please use the newer images.

**Comment by Zac610** [comment]
I can confirm this problem disappeared using void-live-x86_64-musl-20171007-lxqt.iso
