### ISSUE TITLE
Invalid /etc/sudoers if regular user was not created during installation

### ISSUE THREAD

**Issue by giorgiga** [voidlinux/void-mklive#138]
In a freshly installed system (`void-live-x86_64-musl-20171007`, but I guess that doesn't matter), `/etc/sudoers` ends with the lines:

```
# Enable sudo for login ''
 ALL=(ALL) ALL
```

During install I didn't create a user (nor selected `UserAccount`).

**Comment by pullmoll** [comment]
This will be fixed in the next live images.
