### ISSUE TITLE
Creating ISOs in a foreign Linux distribution?

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-mklive#145]
Is there a possibility to use void-mklive for creating ISOs in a foreign Linux distro, as is the case with [xbps-src](https://github.com/voidlinux/void-packages#using-xbps-src-in-a-foreign-linux-distribution) ?

Thanks.

**Comment by tuxlifan** [comment]
You could try to use download the [static binaries](https://www.voidlinux.eu/usage/xbps/#download-static-binaries) and put them in your $PATH.
I didn't test this, tough.

**Comment by cr6git** [comment]
I tried today in Debian:
````
./mklive.sh: 323: ./mklive.sh: xbps-uhelper: not found
[1/9] Synchronizing XBPS repository data...
./mklive.sh: 379: ./mklive.sh: xbps-install: not found
./mklive.sh: 380: ./mklive.sh: xbps-install: not found
./mklive.sh: 382: ./mklive.sh: xbps-query: not found
./mklive.sh: 383: ./mklive.sh: xbps-query: not found
./mklive.sh: 384: ./mklive.sh: xbps-uhelper: not found
[2/9] Installing software to generate the image: base-files libgcc dash coreutils sed tar gawk syslinux grub-i386-efi grub-x86_64-efi squashfs-tools xorriso ...
./mklive.sh: 113: ./mklive.sh: xbps-install: not found
ERROR: Failed to install required software, exiting...
````
It doesn't work. :sob:

**Comment by the-maldridge** [comment]
Given that you clearly don't have the static binaries in path, I'm going to go out on a limb her and not be surprised that it didn't work.

**Comment by tuxlifan** [comment]
@cr6git try the following:
1. cd into the directory where the static binaries are, i.e. `ls ./xbps-install` should run without any error
2. `export PATH=$PATH:$(pwd)`
3. try mklive.sh again

if that still doesn't work (which I think it might because it would probably not find the keys to verify integrity) you can try also to extract the tarball with the static binaries into your root filesystem:

at your own risk:
* `cd /`
* become root
* `tar xf /full/path/to/xbps-static-latest.ARCH-musl.tar.xz`

**Comment by cr6git** [comment]
I will make a new test today! :slightly_smiling_face:

**Comment by cr6git** [comment]
Yes! Today I was able to create a Void ISO in Debian 8.10 Jessie. :tada: 

Just a few things, it was necessary to change this:

`kernel.unprivileged_userns_clone=0` to set it to `1` ([reference](https://superuser.com/a/1122977))

Also, I had to install [liblz4-1](https://packages.debian.org/jessie/liblz4-1) which was missing, and I was forced to install [libreadline7](https://packages.debian.org/sid/libreadline7) from sid because it was not available in jessie.
