### ISSUE TITLE
installer script weirdness

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-mklive#146]
I'm talking about [this line](https://github.com/voidlinux/void-mklive/blob/master/installer.sh.in#L1307) in `installer.sh.in`
````
    sync && sync && sync
````
I have never seen anything like this...
What is the technical justification for three `sync` here?
One `sync` was not enough?

Regards.

**Comment by the-maldridge** [comment]
One sync is generally enough, but it doesn't hurt to have more, and its kind of funny imho.   That line predates me at any rate so the reasoning for its existence is lost to time.

**Comment by cr6git** [comment]
This is technically wrong and I don't find that funny.

**Comment by the-maldridge** [comment]
meh, the line stands.

**Comment by cr6git** [comment]
it's okay.
