### ISSUE TITLE
void-installer on musl does not let configure locale

### ISSUE THREAD

**Issue by adomas187** [voidlinux/void-mklive#151]
Using `void-live-x86_64-musl-20171007.iso` image to install void linux, installer does not let to configure system locale.

Following step by step install with void-installer on step "Locale" as trying to enter menu item screen blinks with text:
`grep: /etc/default/libc-locales: No such file or directory`

Skipping this step still allows system to be installed properly.

Tried also using `void-live-x86_64-20171007.iso` (glibc version) and there is no this issue.

Only happens on **musl** version.

**Comment by maxice8** [comment]
musl doesn't provide different locales, that is glibc only.

**Comment by adomas187** [comment]
Then might be a good idea to remove dummy menu item maybe?
