### ISSUE TITLE
void-live-x86_64-20150403-xfce.iso: No cursor

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-mklive#20]
The cursor is not shown on the screen when using qemu.

Cross checked on the cinnamon ISO, same issue.

**Comment by xtraeme** [comment]
It's a regression of xorg-server-1.17.x.

**Comment by xtraeme** [comment]
Fixed in https://github.com/voidlinux/void-packages/commit/96589a76906948d4c17cd2a805fb40d3f576bc8a
