### ISSUE TITLE
void-live-x86_64-latest-xfce.iso doesn't load

### ISSUE THREAD

**Issue by fcops** [voidlinux/void-mklive#21]
I'm having problems on a 6+ year old PC:

void-live-x86_64-latest-xfce.iso doesn't load, it flashes a message:

    specified group 'kvm' unknown

Void live with base-system for x86_64 gives the same message but it works.

**Comment by xtraeme** [comment]
Are you sure the image you've downloaded is `http://repo.voidlinux.eu/live/void-live-i686-20150403-xfce.iso` that one?

That message should not be critical, i.e just a warning.

**Comment by Ypnose** [comment]
Few days ago (it was monday) I successfully booted and used the <code>void-live-i686-latest-xfce.iso</code>. There was indeed an error about <code>kvm</code> but nothing harmful.

**Comment by xtraeme** [comment]
This has been fixed and new images are now available (from today).

Thanks

**Comment by fcops** [comment]
I'll download again, and keep you posted if I have problems.

Thanks
