### ISSUE TITLE
mkrootfs.sh fails with x86-64/i686

### ISSUE THREAD

**Issue by necrophcodr** [voidlinux/void-mklive#22]
While it appears that the mkrootfs.sh script was not meant to be used for the architectures mentioned (x86-64 and x86)

Reproducing:

Log in as root, and clone the repository to /root/void-mklive  
`cd /root/void-mklive`
`make && ./mkrootfs.sh x86_64`

Result:

> Reconfiguring packages for x86_64 ...
> Running XBPS_ARCH=x86_64 xbps-reconfigure -r /tmp/tmp.Tj1wEjOM25 base-directories ...
> Running chroot /tmp/tmp.Tj1wEjOM25 xbps-reconfigure shadow ...
> chroot: failed to run command 'xbps-reconfigure': No such file or directory
> FATAL: Failed to run chroot /tmp/tmp.Tj1wEjOM25 xbps-reconfigure shadow

**Comment by the-maldridge** [comment]
Seeing as this works now, I'm going to close this issue. feel free to re-open it if you notice problems down the road.
