### ISSUE TITLE
Feature request: mkimage.sh for qemu

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-mklive#24]
Could be helpful for testing purposes to have an easy/automated way to create image for qemu given a 'supported' voidlinux architecture.

**Comment by bougyman** [comment]
+1

**Comment by beefcurtains** [comment]
Agreed it would be useful, but ``qemu foo.iso`` already works.

**Comment by thypon** [comment]
There isn't an iso for arm boards. + what i intend is more a complete qemu image similar to what is created by packer.

**Comment by the-maldridge** [comment]
@thypon the-maldridge/void-packer may be of interest to you.  It depends on as-yet unmerged code in mklive, but other than that it happily generates x86 *.box's.

**Comment by the-maldridge** [comment]
I believe at this time this is resolved.  It's possible to get bootable x86 root filesystems out, which should be sufficient for qemu.
