### ISSUE TITLE
mkrootfs.sh conflict cross-vpkg-dummy-0.20_1 with glibc-2.21_6

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-mklive#30]
When trying to use my local repository to create a cubietruck rootfs using `sudo ./mkrootfs.sh -r /mnt/data/void/binpkgs cubietruck` I see the following error:
```
Running xbps-install -S  --cachedir=/var/cache/xbps  --repository=/mnt/data/void/binpkgs -r /tmp/tmp.tXZN9ka5PV for target armv7l ...
Running xbps-query -R -r /tmp/tmp.tXZN9ka5PV  --cachedir=/var/cache/xbps  --repository=/mnt/data/void/binpkgs -ppkgver base-system for target armv7l ...
base-system-0.108_1
Running xbps-install -S  --cachedir=/var/cache/xbps  --repository=/mnt/data/void/binpkgs -r /tmp/tmp.tXZN9ka5PV -y base-system cubietruck-base for target armv7l ...
CONFLICT: cross-vpkg-dummy-0.20_1 with glibc-2.21_6 in transaction
Transaction aborted due to conflicting packages.
FATAL: Failed to run xbps-install -S  --cachedir=/var/cache/xbps  --repository=/mnt/data/void/binpkgs -r /tmp/tmp.tXZN9ka5PV -y base-system cubietruck-base
```
Am I doing something wrong or missing a point?
The local repository was built up doing `xbps-src -a armv7hf -N pkg base-system` and `... cubieboard2-uboot` (which also creates cubietruck-uboot), `... cubietruck-base` and `... ntp`.

**Comment by xtraeme** [comment]
Hmm, can you paste the output of:

    $ XBPS_ARCH=armv7l xbps-install -d --repository=mnt/data/void/binpkgs -n base-system cubietruck-base

?

**Comment by xtraeme** [comment]
There's no need to run it as root due to `-n` (dry run mode).

**Comment by pullmoll** [comment]
[External link (sprunge.us)](http://sprunge.us/Ycec) due to size :)

**Comment by xtraeme** [comment]
Err, sorry paste the output of this cmd instead:

```
$ XBPS_TARGET_ARCH=armv7l xbps-install -r foo -d --repository=mnt/data/void/binpkgs -n base-system cubietruck-base
```

**Comment by xtraeme** [comment]
I see what's the problem, `musl` is not built as dependency of those pkgs and then `cross-vpkg-dummy` is added because this `provides` musl as virtual package.

Fixing...

**Comment by xtraeme** [comment]
Fixed with https://github.com/voidlinux/void-packages/commit/da14b18651b5094dc83729a874034f478c261d98

Please update and rebuild `base-system` for your target.

**Comment by xtraeme** [comment]
Found the real cause with `glibc`: `libgcc` wasn't built via `base-system` and then `cross-vpkg-dummy` is added to the transaction via virtual packages.

**Comment by pullmoll** [comment]
Thank you for tracking this down!
