### ISSUE TITLE
Grub error during mklive

### ISSUE THREAD

**Issue by mrgreen3** [voidlinux/void-mklive#33]
[6/9] Generating GRUB support for EFI systems...
output file must be specified
Usage: grub-mkstandalone [OPTION] SOURCE...
Generate a standalone image (containing all modules) in the selected format
  -h, --help              print this message and exit
  -v, --version           print the version information and exit
  -o, --output=FILE       save output in FILE [required]
  -d, --directory=DIR     use images and modules under DIR
                          [default=/usr/lib/grub/<platform>]
  -O, --format=FORMAT     generate an image in FORMAT

                          available formats: i386-coreboot i386-multiboot
                          i386-pc i386-pc-pxe i386-efi i386-ieee1275
                          i386-qemu x86_64-efi mipsel-yeeloong-flash
                          mipsel-fuloong2f-flash mipsel-loongson-elf
                          powerpc-ieee1275 sparc64-ieee1275-raw
                          sparc64-ieee1275-aout ia64-efi mips-arc
                          mipsel-qemu_mips-elf mips-qemu_mips-flash
                          mipsel-qemu_mips-flash  mips-qemu_mips-elf

  -C, --compression=(xz|none|auto)
                          choose the compression to use
  --modules=MODULES       pre-load specified modules MODULES
  --grub-mkimage=FILE     use FILE as grub-mkimage

Report bugs to <bug-grub@gnu.org>.
ERROR: Failed to generate EFI loader

Command run sudo ./mklive.sh -a i686 (from x86_64 based system)

Same error with x86_64 stock files no additions or changes,,,,

**Comment by xtraeme** [comment]
Fixed
