### ISSUE TITLE
Using standard mklive scripts -c 

### ISSUE THREAD

**Issue by mrgreen3** [voidlinux/void-mklive#37]
-rw-r--r-- 1 root    root  198180864 Jun 21 08:02 void-live-x86_64-4.0.5_2-20150621.iso
    drwxr-xr-x 2 root    root      16384 Jun 21 07:58 xbps-cachedir-x86_64

Using mklive.sh no modifications

**Comment by xtraeme** [comment]
THIS IS HOW IT WORKS, STOP SUBMITTING THESE USELESS PROBLEM REPORTS
