### ISSUE TITLE
Release new live isos

### ISSUE THREAD

**Issue by trufae** [voidlinux/void-mklive#60]
The ones in this repo are from november:

http://repo.voidlinux.eu/live/current/

we should setup some kind of monthly scheduled isos or so. what do you think?

**Comment by pullmoll** [comment]
I agree that releasing new ISOs would be fine.

However I think that a scheduled time to create them automatically may interfere with times where too many of the packages are in a flow (so bumping) or even broken.

**Comment by Vaelatern** [comment]
The old isos work just fine. There are no incompatibilities that prevent `xbps-install -Su` in them. Until that happens for some reason, there probably isn't a reason to update them.

**Comment by Duncaen** [comment]
Getting current kernel versions into the image would be a good reason, I think there where a lot of problems with the kernel used in current images.

**Comment by trufae** [comment]
i had two problems with the current iso:

i have with current iso is partitioning, because its confusing and
selecting gpt/efi/... only happens once. we should probably have automatic
partitioning modes like : use full disk, etc, and just do the partitions
and use swap+ext4, and handle luks, etc..

also, the other problem is that all live isos cannot be installed. i tried
with mate+musl+x86_64, and the void-installer script was failing in many
ways, the most problematic one was the network setup which was ok in the
shell, but the installer reports errors and says it cannot access the
network

i understand those issues will be also reproducible with latest
void-installer, and this is probably not the right place to post that.. but
i think users feel like they are downloading an abandoned distro, or not a
really rolling release one when they saw the iso is that old.

**Comment by the-maldridge** [comment]
This is a continuous issue that we are working to resolve, as such I am going to close this bug.
