### ISSUE TITLE
Trying to ssh into void in my raspberry give me a `Permission denied, please try again.` error.

### ISSUE THREAD

**Issue by onodera-punpun** [voidlinux/void-mklive#64]
Using "root" and "voidlinux" as password.

Using `void-rpi-musl-rootfs-20160316.tar.xz`

**Comment by Gottox** [comment]
This was a bug in older releases, but the current image should work.

Can you connect a screen/keyboard and have a look at the sshd_config? PermitRootLogin should be yes.

**Comment by onodera-punpun** [comment]
yes, I PermitRootLogin is indeed yes so I really don't know what the problem...

**Comment by Gottox** [comment]
on the pi:
```
# sv stop sshd
# /usr/sbin/sshd -d
```
Then login via ssh to see whats going on.

**Comment by onodera-punpun** [comment]
Sorry, this seemed to be a problem I created myself by symlinking .ssh from another location with the wrong permissions!
