### ISSUE TITLE
remove anon from /etc/sudoers

### ISSUE THREAD

**Issue by grafoo** [voidlinux/void-mklive#76]
when using the **Local (Packages from ISO image)** installation source, `/etc/sudoers` will be copied over to the resulting installation filesystem which includes the line `anon ALL=(ALL) NOPASSWD: ALL`. Though there's actually no such user in the newly created system, adding this account in the future will lead to serious security implication when the person of doing so is unaware of anon's sudo privileges.

**Comment by jcjordyn130** [comment]
This bit of code I found in the void-installer on line 1211 should do just that.
`sed -i -e "/$USERNAME ALL=.*/d" $TARGETDIR/etc/sudoers`

**Comment by Vaelatern** [comment]
Can either behaviour be confirmed?

**Comment by ebfe** [comment]
7e21c2f151b4363ae1704306125b495ab528c2cd, fixed months ago. Still an issue with the latest images...

**Comment by Vaelatern** [comment]
@xtraeme Can we have new images, please?

**Comment by jcjordyn130** [comment]
Last I herad he is very busy.

**Comment by jcjordyn130** [comment]
*heard

**Comment by the-maldridge** [comment]
New images have been spun which include the patches discussed in this issue.  If you still believe this fault exists, please open a new issue.
