### ISSUE TITLE
Change default hostname on ARM SBCs

### ISSUE THREAD

**Issue by whitephoenix0** [voidlinux/void-mklive#78]
I installed void on my raspberry pi model B, as per https://wiki.voidlinux.eu/Raspberry_Pi#rootfs-install
and I noticed that the default hostname is "void-live". This is just a minor suggestion that the default hostname be changed to something more descriptive. "Void-live" sounds like you are on a live usb preparing to install, but this is a fully installed and configured system. For a raspberry pi system it should be something like "void-pi". Super insignificant nitpick though.

**Comment by the-maldridge** [comment]
Installing to a Pi isn't really "installing" per se, its more unpacking a prebuilt system.  As such you can easily change the hostname by putting your preferred hostname into ${TARGET}/etc/hostname.
