### ISSUE TITLE
mkimage.sh.in: wrong partition activated?

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-mklive#80]
The sfdisk command for beaglebone looks like:
```
    sfdisk ${FILENAME} <<_EOF
label: dos
2048,${BOOT_FSSIZE},b
${BOOT_SIZE},+,L,*
_EOF
```
which makes the second partition active (`*`).
According to the [WIKI](https://wiki.voidlinux.eu/Beaglebone) the **first** partition has to be activated.

Even after manually modifying the active partitions the (locally) generated `void-beaglebone-<date>.img` does not boot on my beaglebone black...

**Comment by pullmoll** [comment]
Confirmation: Now I changed the lines to:
```
   sfdisk ${FILENAME} <<_EOF
label: dos
2048,${BOOT_FSSIZE},b,*
${BOOT_SIZE},+,L
_EOF
```
recreated the `void-beaglebone-<date>.img` and after copying it to an SD card the image booted.

**Comment by pullmoll** [comment]
Oh, and I didn't see this one: I don't see `BOOT_SIZE` being defined, so the line will expand to `,+,L`.
This seems to work by accident, while I guess the intention was to explicitly specify `${BOOT_FSSIZE}` here.

**Comment by xtraeme** [comment]
Oh right, it's a typo. Thanks!
