### ISSUE TITLE
Non working image created when running ./build-arm-images.sh beaglebone

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-mklive#81]
I tried to create a beaglebone (black) image after building the required armv7hf pkgs locally and specifying `-r /path/to/my/bindir` to the script. Everything went fine and a `void-beaglebone-<date+time>.img.xz` was created.

Interestingly the image does not even try to boot on the bbb, i.e. no LED of the 4 user LEDs is lit when I hold the `boot` button. This means that not even MLO is loaded from the FAT32 parition as far as I can tell. The current Debian eMMC installer image is booting just fine, as is the most recent live image from https://repo.voidlinux.eu/live/20160316/ .

I have not yet verified if the MLO image, or u-boot.img, is the same as the ones on the published live rootfs. Something is going really, really wrong here IMHO. Did anyone else try to build their own binpkgs and creating an arm rootfs from that?

**Comment by CMB** [comment]
I think https://github.com/voidlinux/void-mklive/pull/89 fixes this.
For me, it was creating images that didn't even have a partition table
or other data and claiming that it was successful.
