### ISSUE TITLE
musl images and stale repodata

### ISSUE THREAD

**Issue by CMB** [voidlinux/void-mklive#90]
When building musl images / tarballs, mklive and mkrootfs pull from
repo.voidlinux.eu/current/ as well as the musl repo.
But repo.voidlinux.eu/current/ contains some stale *-musl-repodata
files.  These repodata files have some noarch packages in them, some
of which are out of date.  E.G., when building an rpi2-musl rootfs
yesterday, mkrootfs tried to grab tzdata-2016g_2.
Maybe I should file this issue against void-packages instead.
I filed it here because AFAIK void-mklive is the only thing broken
by these stale repodata files.

**Comment by chneukirchen** [comment]
Should be cleaned up now. Thanks.
