### ISSUE TITLE
Request: Give the user a choice before installing non-free firmware

### ISSUE THREAD

**Issue by greencopper** [voidlinux/void-mklive#93]
Hi,

It has come to my attention that Void Linux installs non-free firmware without letting the user know about it.

https://forum.voidlinux.eu/t/unacceptable-nvidia-binary-blob-in-base-install/

> It never runs on your CPU and it doesn't get touched at all if its not needed for you hardware.

Even though it can be argued that you cannot avoid non-free firmware completely in any hardware, I believe we should make it so a user explicitly needs to enable this before it's run.

It's not because non-free is avoided by this, it clearly isn't as it's already located on most ROMS, but it's so the user knows everything about what gets installed and he actually has a choice to avoid it.

During installation of Debian, if the installer detects hardware that requires some non-free binary firmware, the user is asked if he want to provide the non-free blob. Or he can choose to run the "netinst" version with non-free firmware.

Could we not make it so the user is asked in Void Linux like in Debian?

**Comment by emdete** [comment]
i like this way of transperency and would even go further to confirm the load on first use. so you can install all blobs for all potential hw and will be asked to activate if needed (i.e. something is hotplugged). don't know if that is easily feasable...

**Comment by Gottox** [comment]
We ship these binary blobs as it is a very easy way to get a working system for our users.

If you like to implement a more libre approach on the base of Void Linux at the cost of non-usable system feel free to do so. For the individual user that cares about a libre system, I [opened a PR](https://github.com/voidlinux/void-packages/pull/5483) that allows to replace the linux metapackage with a linux-free metapackage that won't depend on blobs. But that's as far as it will get. We as the maintainers and developers are confident that for now we're doing the right thing with shipping these packages.

**Comment by chneukirchen** [comment]
It would be good if someone could confirm these blobs are used with the kernel drivers, and not only for `nvidia-dkms` etc. Else we could make the proprietary drivers depend on the firmware.

**Comment by pullmoll** [comment]
FWIW the amdgpu.h file contains a lot of `const struct firmware` fields where the various bits and pieces are defined. They are loaded, iff you happen to use a main board with some of the AMD CPU/GPU mashups as I did until recently. Now with an Intel i7 core there is nothing loaded.

The firmware is installed with the kernel *just to be ready* for the case where it needs to be loaded. It is not touched at all, if the hardware you use does not require it. For anyone who doesn't need them, they are just data that is never read.

Purchasing hardware that works without this firmware blobs is the only way to have a *free* Linux, i.e. one where there are no blobs to be loaded into E²PROM or RAM areas of the chips in question.

IMHO we should not start alienating users by not providing these blobs or forcing them to use *install disks* (do they still exist?) or *USB sticks* with the extra data.

**Comment by greencopper** [comment]
I don't understand how Debian, Devuan, Linux Mint and others then get this stuff working? When I install Debian I don't get this firmware and my Nvidia card works fine without it using nouveau.

**Comment by pullmoll** [comment]
I said that *I think*. I may be wrong with regards to nvidia. I never had such a card.

**Comment by xtraeme** [comment]
The firmware for nvidia is only required for nouveau, not the proprietary
drivers.

2017-01-07 22:58 GMT+01:00 Jürgen Buchmüller <notifications@github.com>:

**Comment by greencopper** [comment]
> The firmware for nvidia is only required for nouveau, not the proprietary drivers.

I am running nouveau on Debian, on Devuan, and on Linux Mint and I don't get the firmware! If I try to install Void on those very same boxes, I get the firmware.

**Comment by greencopper** [comment]
There is also the point that it really undermines the entire purpose of having a non-free repo to begin with. It makes no sense to have the non-free repo then.

**Comment by Gottox** [comment]
Yes you're right and no we won't change that.

**Comment by greencopper** [comment]
> Yes you're right and no we won't change that.

Well, then at least inform people on the website that the non-free repo doesn't mean that's the only non-free stuff on Void Linux and that non-free firmware gets installed if hardware needs it.

Having the non-free repo is MISGUIDING!

**Comment by Gottox** [comment]
I don't think that's neccassary. ArchLinux, Ubuntu, Alpine, etc... All ship the blobs in their base without telling it on their websites and libre distributions are very anxious to tell that they don't ship them.

**Comment by greencopper** [comment]
That's not true.

Alpine and Arch haven't got any non-free repos, so there is no misguidance here. They don't need to tell anything because they don't cause any confusion or misguidance with "non-free" terminology.

Ubuntu doesn't ship blobs in their base, Ubuntu splits the packages up into two, "linux-firmware", and "linux-firmware-nonfree" and it clearly states on their website that: "_Note that the linux-firmware-nonfree package is not installed by default._"

Void Linux on the other hand has a non-free repo, but at the same time also ships non-free in the base without letting people know. I think this is misguiding.

I think the best would be to either remove the non-free repo as it really serves no purpose what so ever, or use another terminology.

**Comment by Gottox** [comment]
Yes your totally right and no we won't do that at this point of time.

**Comment by greencopper** [comment]
Actually, I want to correct my self a bit and apologize as well as I have overlooked the statement on the "about" page on the Void Linux website:

> Excluding binary kernel blobs, a base install is composed entirely of free software, but users can access an official nonfree repository to install proprietary software.

https://wiki.voidlinux.eu/Void_Linux

So **no** misguiding actually takes place unlike the case with OpenBSD.
