### ISSUE TITLE
Installer Fails on ESXi

### ISSUE THREAD

**Issue by cliii** [voidlinux/void-mklive#97]
The script, `installer.sh`, fails with the error, `Network is unaccessible, please setup it properly.` on VMware ESXi. The Void Linux installation was attempted on ESXi 6.0.

**Comment by the-maldridge** [comment]
@cliii Can you jump to another tty and verify that you have at least one non-loopback adapter that you can manually bring up?

The installer is pretty much just a complicated shell script, its not very intelligent for cases we don't explicitly test.

**Comment by cliii** [comment]
The installer tries to use `eno16777736`. I don't see this device, or any networking device, in `/dev`. I did try it manually anyway, `ip addr add 1.2.3.4 dev eno16777736` with the same result as the installer.

**Comment by radare** [comment]
i had the same device name, and dhcp stopped working, did this to at least have a normal interface name

ip dev link eno167777736 down
ip dev link eno167777736 name eth0
ip dev link eth0 up

**Comment by cliii** [comment]
I don't see a reference to a `dev` *command* in the `ip` manual, only in arguments to commands. Did you mean as follows?

    ifconfig eno16777736 down  
    ip link set eno16777736 name eth0  
    ifconfig eth0 up
 
Still fails with `Unable to configure device eth0.`

**Comment by Duncaen** [comment]
> I did try it manually anyway, ip addr add 1.2.3.4 dev eno16777736 with the same result as the installer.

What is the result?
If you setup a static network, you are responsible to set it up (address, default route, nameservers...).

**Comment by cliii** [comment]
Uh, yeah... thank you? If you create a Linux distribution, you are responsible to set it up correctly  (detecting devices, installation scripts, ...).

**Comment by Vaelatern** [comment]
Instead of 
```
ip dev link eno167777736 down
ip dev link eno167777736 name eth0
ip dev link eth0 up
```
I think you want
```
ip link dev eno167777736 down
ip link dev eno167777736 name eth0
ip link dev eth0 up
```

**Comment by Duncaen** [comment]
```
ip link set eno167777736 down
ip link set eno167777736 name eth0
ip link set eth0 up
```
@cliii I guess I forgot about the paycheck that makes me or any other contributor responsible to work for you. Not sure why you feel like answering to me like this.
Anyways, my response was about you having to setup a static network, its static there is nothing like dhcp that would set it up automatically, that's not how it works.
And you did not respond to what the result is.

**Comment by cliii** [comment]
omfg... nevermind. all other distress work. forget it.
