### ISSUE TITLE
mklive.sh script fails when there's a space in the name of one of its parent directory

### ISSUE THREAD

**Issue by greygjhart** [voidlinux/void-mklive#99]
Well, clearly a cosmetics issue, very easy to workaround but still, I think that kind of scripts ought to be robust enough to run no matter where it's installed.

It's very easy to reproduce, just clone into 'void mklive' instead of 'void-mklive' and you should see a 'void' directory appear next to it while running `./mklive.sh`. It's also very clear why this happen, almost all location variables appear unquoted in the script like so

`mkdir -p $ROOTFS/$f`

I've [forked](https://github.com/greygjhart/void-mklive) the project to work on the issue and I'll make a PR if that's fine with you guys (I could totally understand that you don't want the variables in your script to get massively double-quoted for such a minor gain as fixing the issue I'm reporting). I'm almost there but I think I may have been to quote-eager, now I get a weird ' /' getting created in the root of the new system being generated and step 4 fails with dracut not finding the tools it needs.

**Comment by the-maldridge** [comment]
@greygjhart do you intend to complete your PR for quoting of variables?

**Comment by greygjhart** [comment]
Yeah, sorry about that. I haven't worked on the project for months. I might do that one day when I have time to work again on my void system but you can totally close my issue for now.

**Comment by the-maldridge** [comment]
Feel free to reopen this issue if and when you pick back up this project.
